task:
  name: PegInHole
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 1.5
    episodeLength: 500
    enableDebugVis: false
    clipObservations: 5.0
    clipActions: 1.0
    startPositionNoise: 0.0
    startRotationNoise: 0.0
    numProps: 16
    aggregateMode: 3
    actionScale: 7.5
    dofVelocityScale: 0.1
    distRewardScale: 2.0
    rotRewardScale: 0.5
    aroundHandleRewardScale: 0.25
    openRewardScale: 7.5
    fingerDistRewardScale: 5.0
    actionPenaltyScale: 0.01
    asset:
      assetRoot: ../../assets
      assetFileNameFranka: urdf/franka_description/robots/franka_panda.urdf
      assetFileNameCabinet: urdf/sektion_cabinet_model/urdf/sektion_cabinet_2.urdf
    enableCameraSensors: false
  sim:
    dt: 0.0166
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 12
      num_velocity_iterations: 1
      contact_offset: 0.005
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 1048576
      num_subscenes: ${....num_subscenes}
      contact_collection: 1
  task:
    randomize: false
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:PegInHole,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0005
      lr_schedule: adaptive
      kl_threshold: 0.008
      score_to_win: 10000
      max_epochs: ${resolve_default:1500,${....max_iterations}}
      save_best_after: 200
      save_frequency: 100
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 8192
      mini_epochs: 8
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
multi_gpu: false
headless: false
